import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import compliance from "../../assets/compliance/compliance.webp";
import ComplianceOffer from "../elementalComponent/ComplianceOffer";
import ComplianceInnovation from "../elementalComponent/ComplianceInnovation";
import MaxtronLead from "../elementalComponent/MaxtronLead";
import ComplianceChoose from "../elementalComponent/ComplianceChoose";
import ComplianceFooter from "../elementalComponent/ComplianceFooter";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
const Compliance = () => {
    return (_jsxs(_Fragment, { children: [_jsxs(Helmet, { children: [_jsx("title", { children: "Compliance | Maxtron" }), _jsx("meta", { name: "description", content: "Stay ahead of digital asset legislation with Maxtron's compliance solutions. Ensure your projects are legally sound and future-ready." }), _jsx("link", { rel: "canonical", href: "https://www.maxtron.ai/compliance" }), _jsx("meta", { name: "robots", content: "index, follow" }), _jsx("meta", { httpEquiv: "X-Robots-Tag", content: "index, follow" }), _jsx("meta", { property: "og:title", content: "Compliance | Maxtron" }), _jsx("meta", { property: "og:description", content: "Stay ahead of digital asset legislation with Maxtron's compliance solutions. Ensure your projects are legally sound and future-ready." }), _jsx("meta", { property: "og:image", content: "https://www.maxtron.ai/src/assets/MaxtronLogo.png" }), _jsx("meta", { property: "og:url", content: "https://www.maxtron.ai/compliance" }), _jsx("meta", { property: "og:type", content: "website" })] }), _jsx("div", { className: "w-full", children: _jsxs("div", { className: "w-full max-w-[96rem] mx-auto px-4 sm:px-7 md:px-16 xl:px-16 py-5 sm:py-6 md:py-8 lg:py-10 xl:py-12 ", children: [_jsxs("div", { className: "flex flex-col lg:flex-row bg-[#F3EBFC] ", children: [_jsxs("div", { className: "w-full lg:w-1/2 px-8 sm:px-14 py-12", children: [_jsxs("div", { className: "flex items-center gap-2 bg-[#7A35C1] px-5 mb-10 w-fit", children: [_jsx("p", { className: "bg-white w-3 h-3" }), _jsx("p", { className: "text-white text-base font-[switzer] py-3 uppercase", children: "Powering Trust, Across Borders and Blockchains" })] }), _jsx("div", { className: "mb-6", children: _jsxs("h1", { className: "text-[#2A2A2A] text-5xl xl:text-6xl font-normal leading-tight", children: ["A New Era of Digital", _jsx("br", {}), "Asset Legislation"] }) }), _jsx("p", { className: "text-[#2A2A2A] text-base font-openSansHebrew leading-[150%] mb-16 lg:mb-28", children: "At Maxtron.ai, compliance isn't an afterthought\u2014it's a competitive advantage. As global digital asset laws evolve, our platform ensures your projects stay legally sound, strategically positioned, and future-ready" }), _jsx("div", { children: _jsx(Link, { to: "/contact", children: _jsx("button", { className: "bg-[#7A35C1] text-white text-base font-[switzer] px-5 py-3 hover:bg-[#D8D0F4] hover:text-black transition-transform transform hover:scale-105", children: "CONTACT US" }) }) })] }), _jsxs("div", { className: "w-full lg:w-1/2 flex items-end bg-white flex-col", children: [_jsx("div", { className: "bg-white w-full h-full" }), _jsx("div", { className: "bg-[#F3EBFC] w-full h-full" }), _jsx("div", { children: _jsx("img", { src: compliance, alt: "compliance", className: "w-full" }) })] })] }), _jsx(ComplianceOffer, {}), _jsx(ComplianceInnovation, {}), _jsx(MaxtronLead, {}), _jsx(ComplianceChoose, {}), _jsx(ComplianceFooter, {})] }) })] }));
};
export default Compliance;
