import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams } from "react-router-dom";
import ContactForm from "../ContactForm";
import create4 from "../../assets/internal/create4.svg";
const ProcessSteps = ({ processSteps, }) => (_jsx("div", { className: "border-l border-[#D9D9D9]", children: processSteps.map((step, index) => (_jsxs("div", { className: "mb-12 pl-4 relative", children: [_jsx("div", { className: "w-4 h-4 bg-purple-500 rounded-full absolute left-[-10px] top-2" }), _jsx("h2", { className: "text-2xl font-semibold mb-2", children: step.title }), step.description.length > 0 && step.description[0] !== "" && (_jsx("ul", { className: "list-disc pl-6 mt-4", children: step.description.map((desc, idx) => desc !== "" && (_jsx("li", { className: "mb-2 text-sm", children: desc }, idx))) }))] }, index))) }));
const InternalPage = ({ caseStudies }) => {
    const { id } = useParams();
    const caseStudy = caseStudies[Number(id)];
    if (!caseStudy) {
        return (_jsx("div", { className: "container mx-auto px-4 py-8", children: "Case study not found" }));
    }
    const { title, subtitle, heroImage, industryInfo, projectDuration, clientSatisfaction, problemSolutionResult, techs, keyFeatures, bgImage, } = caseStudy;
    return (_jsxs("div", { children: [_jsxs("div", { className: "relative z-10 pt-32 lg:pt-16 text-center internal_page_hero_img px-4 sm:px-6 lg:px-8", children: [_jsx("div", { className: "absolute inset-0 bg-cover h-[78%]  bg-center z-1", style: { backgroundImage: `url(${bgImage})` } }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-[#8941C4] to-transparent opacity-80 z-5" }), _jsx("h1", { className: "relative z-15 text-3xl sm:text-4xl lg:text-5xl font-bold text-white", children: title }), _jsx("p", { className: "relative z-15 text-base sm:text-lg lg:text-xl mt-2 text-white", children: subtitle }), _jsx("img", { src: heroImage, alt: "hero", className: `
    relative 
    ${Number(id) === 1 ? "lg:w-[64%]" : "lg:w-[50%]"}
    h-[90%]
    ${Number(id) === 2 ? "w-[80%] h-[80%]" : "w-[100%] h-[90%]"}
    
  ` })] }), _jsxs("div", { className: "container mx-auto mt-8 flex flex-wrap lg:flex-nowrap", children: [_jsxs("div", { className: "w-full lg:w-[30%] lg:m-0 p-4 bg-[#F2EEEF] rounded-lg h-fit mx-4 lg:mr-8", children: [_jsxs("div", { className: "py-2 mt-4", children: [_jsx("h2", { className: "text-xl font-bold mb-2", children: "INDUSTRY" }), _jsx("p", { className: "text-lg", children: industryInfo })] }), _jsxs("div", { className: "py-2 mt-4", children: [_jsx("h2", { className: "text-xl font-bold mb-2", children: "PROJECT DURATION" }), _jsx("p", { className: "text-lg", children: projectDuration })] }), _jsxs("div", { className: "py-2 mt-4", children: [_jsx("h2", { className: "text-xl font-bold mb-2", children: "CLIENT SATISFACTION" }), _jsxs("p", { className: "text-lg flex items-center", children: [[...Array(5)].map((_, i) => (_jsx("span", { className: "text-yellow-400", children: "\u2605" }, i))), clientSatisfaction.toFixed(1)] })] })] }), _jsxs("div", { className: "w-full lg:w-[70%] p-4 lg:p-0", children: [title.toUpperCase().includes("DIAL247.AI") && (_jsx("h2", { className: "text-xl font-bold mb-6", children: "How Maxtron Helped, Build the Revolutionary Dial 247 AI Calling Tool" })), problemSolutionResult.map((section, index) => (_jsxs("div", { className: "mb-10 pb-10 border-b border-gray-200 last:border-b-0 last:mb-0 last:pb-0", children: [_jsx("h2", { className: "text-2xl font-bold mb-6", children: section.heading }), section.subheading && (_jsx("h3", { className: "text-xl font-semibold mb-4", children: section.subheading })), _jsx("ul", { className: "list-disc", children: section.points.map((point, idx) => typeof point === "string" ? (_jsx("p", { className: "mt-4", children: point }, idx)) : (
                                        // <p key={idx} className="mt-3">
                                        //     <h3 className="text-xl font-semibold mb-4">{point.title}</h3>
                                        //     <p className="list-disc pl-5 mt-2">
                                        //         {point.details.map((detail, detailIdx) => (
                                        //             <p key={detailIdx} className="mt-2">{detail}</p>
                                        //         ))}
                                        //     </p>
                                        // </p>
                                        _jsx("p", { children: "jhfdb" }))) })] }, index)))] })] }), _jsx("div", { className: "container mx-auto py-12", children: _jsx("div", { className: "flex mx-4 flex-wrap lg:flex-nowrap items-center justify-between", children: _jsxs("div", { className: "w-full lg:w-2/3", children: [techs.length > 0 && (_jsx("h2", { className: "text-3xl font-bold mb-6", children: "Tech used" })), _jsx("div", { className: "flex flex-wrap mb-8", children: techs.map((tech, index) => (_jsxs("div", { className: "flex items-center mr-2 mb-4 bg-[#D9D9D9] py-1 px-2 rounded-lg", children: [tech.icon && _jsx(tech.icon, {}), _jsx("span", { children: tech.name })] }, index))) }), _jsxs("div", { className: "container mx-auto py-12", children: [_jsx("h2", { className: "text-3xl font-bold mb-8", children: caseStudy.theprocessText }), _jsx(ProcessSteps, { processSteps: caseStudy.processSteps })] })] }) }) }), _jsx("div", { className: "container mx-auto pt-4 px-4 lg:px-0 flex flex-wrap lg:flex-nowrap items-center justify-between", children: _jsxs("div", { className: "w-full lg:w-1/2 lg:pl-8 lg:pr-4", children: [_jsx("h2", { className: "text-3xl font-bold mb-6", children: "Key Features" }), _jsx("ul", { className: "list-none", children: keyFeatures.map((feature, index) => (_jsx("li", { className: "mb-4", children: typeof feature === "string" ? (_jsx("p", { className: "text-sm", children: feature })) : (_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold mb-2", children: feature.title }), _jsx("ul", { className: "list-disc pl-5", children: feature.details.map((detail, detailIndex) => (_jsx("li", { className: "text-sm mb-1", children: detail }, detailIndex))) })] })) }, index))) }), title.toUpperCase().includes("CREATE PROTOCOL") && (_jsx("img", { src: create4, alt: "Key Features Diagram", className: "w-full h-auto rounded-lg shadow-lg" }))] }) }), _jsx("div", { className: "container mx-auto my-16 px-4", children: _jsx(ContactForm, {}) })] }));
};
export default InternalPage;
