import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const MoreCaseStudies = ({ setShowMoreCaseStudies, }) => {
    const handleSubmit = (e) => {
        e.preventDefault();
        setShowMoreCaseStudies(false);
    };
    return (_jsx("div", { className: "md:px-12", children: _jsxs("div", { className: "container mx-auto px-4 flex flex-col items-center", children: [_jsx("h2", { className: "text-3xl font-extrabold pb-8 text-black mb-6", children: "Get A Specific Use-Case Study From Us" }), _jsx("div", { className: "w-full lg:w-2/5 bg-white p-8 shadow-lg rounded-lg", children: _jsxs("form", { onSubmit: handleSubmit, className: "text-start", children: [_jsxs("div", { className: "mb-4", children: [_jsx("label", { htmlFor: "fullName", className: "block text-gray-700 font-bold mb-2", children: "Name" }), _jsx("input", { type: "text", id: "fullName", name: "fullName", className: "w-full p-3 border border-gray-300 rounded-lg placeholder-bg", placeholder: "Name" })] }), _jsxs("div", { className: "mb-4", children: [_jsx("label", { htmlFor: "email", className: "block text-gray-700 font-bold mb-2", children: "Work Email" }), _jsx("input", { type: "email", id: "email", name: "email", className: "w-full p-3 border items-start border-gray-300 rounded-lg placeholder-bg", placeholder: "Email" })] }), _jsxs("div", { className: "mb-4", children: [_jsx("label", { htmlFor: "companyName", className: "block text-gray-700 font-bold mb-2", children: "Company Name" }), _jsx("input", { type: "text", id: "companyName", name: "companyName", className: "w-full p-3 border border-gray-300 rounded-lg placeholder-bg", placeholder: "Company Name" })] }), _jsxs("div", { className: "mb-6", children: [_jsx("label", { htmlFor: "useCase", className: "block text-gray-700 font-bold mb-2", children: "On Which Use-Case Would You Like To Have A Case Study?" }), _jsx("textarea", { id: "description", name: "description", className: "w-full p-3 border border-gray-300 rounded-lg placeholder-bg", placeholder: "Description" })] }), _jsx("div", { className: "text-right", children: _jsx("button", { type: "submit", className: "px-6 py-3 text-black font-bold rounded-lg border-[2px] border-black bg-white hover:bg-black hover:text-white transition-colors duration-300", children: "Submit" }) })] }) })] }) }));
};
export default MoreCaseStudies;
