import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Web3MarketingHeroSection from "../Web3MarketingHeroSection";
import MarketingCase from "../elementalComponent/MarketingCase";
import Web3MarketingOffers from "../elementalComponent/Web3MarketingOffers";
import Web3MarketingFooter from "../elementalComponent/Web3MarketingFooter";
import Web3Speed from "../elementalComponent/Web3Speed";
import FullStackMarketing from "../elementalComponent/FullStackMarketing";
import { Helmet } from "react-helmet-async";
const Web3Marketing = () => {
    return (_jsxs(_Fragment, { children: [_jsxs(Helmet, { children: [_jsx("title", { children: "Best Web3 Marketing & PR Agency | Top Web3 digital marketing agency" }), _jsx("meta", { name: "description", content: "Looking for the best Web3 marketing agency? We are a leading Web3 marketing company offering PR, advertising, and digital marketing solutions for blockchain brands. Partner with top Web3 marketing experts today." }), _jsx("link", { rel: "canonical", href: "https://www.maxtron.ai/web3-marketing" }), _jsx("meta", { name: "robots", content: "index, follow" }), _jsx("meta", { httpEquiv: "X-Robots-Tag", content: "index, follow" }), _jsx("meta", { property: "og:title", content: "Web3 Marketing | Maxtron" }), _jsx("meta", { property: "og:description", content: "Maxtron's Web3 Marketing services accelerate your business growth with innovative blockchain and digital marketing solutions." }), _jsx("meta", { property: "og:image", content: "https://www.maxtron.ai/src/assets/MaxtronLogo.png" }), _jsx("meta", { property: "og:url", content: "https://www.maxtron.ai/web3-marketing" }), _jsx("meta", { property: "og:type", content: "website" })] }), _jsxs("div", { id: "Home", children: [_jsx("a", { href: "#main-content", className: "sr-only focus:not-sr-only focus:absolute focus:z-50 focus:p-4 focus:bg-white focus:text-black", children: "Skip to main content" }), _jsxs("main", { id: "main-content", role: "main", children: [_jsx(Web3MarketingHeroSection, {}), _jsx("section", { id: "full-stack-marketing", "aria-label": "Full Stack Marketing", children: _jsx(FullStackMarketing, {}) }), _jsx("section", { id: "web3marketing-offers", "aria-label": "Web3 Offers", children: _jsx(Web3MarketingOffers, {}) }), _jsx("section", { id: "marketing-case", "aria-label": "Marketing Case", children: _jsx(MarketingCase, {}) }), _jsx("section", { id: "web3-speed", "aria-label": "Web3 Speed", children: _jsx(Web3Speed, {}) }), _jsx("section", { id: "web3marketing-footer", "aria-label": "Web3 Marketing Footer", children: _jsx(Web3MarketingFooter, {}) })] })] })] }));
};
export default Web3Marketing;
