import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import logo from "../assets/logo.svg";
const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    const toggle = () => {
        setIsOpen(!isOpen);
    };
    const { pathname } = useLocation();
    useEffect(() => {
        window.scrollTo(0, 0);
    }, [pathname]);
    return (_jsx("nav", { className: "fixed bg-custom-gradient p-4   left-0 right-0 z-50", children: _jsxs("div", { className: "container mx-auto flex   justify-between items-center", children: [_jsxs("div", { className: " w-full lg:flex hidden  justify-between ", children: [_jsx(Link, { to: "/", children: _jsx("img", { src: logo, alt: "maxtron logo", className: "" }) }), _jsx("div", { className: `lg:flex relative  lg:items-center md:w-auto ${isOpen ? "block" : "hidden"}`, children: _jsxs("div", { className: "text-white font-OpenSans capitalize lg:flex md:space-x-4", children: [_jsx(NavLink, { onClick: () => setIsOpen(false), to: "/", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Home" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/services", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Services" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/industries", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Industries" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/case-studies", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Case Studies" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/about", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "About Us" }), _jsx("button", { className: "block mt-4 text-sm md:inline-block md:mt-0 rounded-lg p-2 bg-[#F5F5F5] text-black", children: _jsx(Link, { to: "/Contact", children: "Contact Us" }) }), _jsx("button", { onClick: () => {
                                            window.open("https://calendly.com/business-maxtron/30min");
                                        }, className: "block mt-4 text-sm md:inline-block md:mt-0 capitalize rounded-lg p-2 bg-[#F5F5F5]  text-black", children: "book a call" })] }) })] }), _jsxs("div", { className: "lg:hidden  flex justify-between w-full", children: [_jsxs("div", { className: `flex relative justify-between items-center w-full`, children: [_jsx(Link, { to: "/", className: `${isOpen ? "hidden" : "flex"}`, children: _jsx("img", { src: logo, alt: "maxtron logo", className: "" }) }), _jsx("div", { className: `lg:hidden flex ${isOpen ? "hidden" : "flex"}`, onClick: toggle, children: _jsx("button", { className: "text-white focus:outline-none flex", children: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: isOpen ? "" : "M4 6h16M4 12h16m-7 6h7" }) }) }) }), _jsxs("div", { className: `text-white font-OpenSans capitalize lg:flex md:space-x-4  ${isOpen ? "block" : "hidden"}`, children: [_jsx(NavLink, { onClick: () => setIsOpen(false), to: "/", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Home" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/services", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Services" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/industries", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Industries" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/case-studies", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "Case Studies" }), _jsx(NavLink, { onClick: () => setIsOpen(false), to: "/about", className: "block mt-4 text-sm md:inline-block md:mt-0 hover:bg-[#F5F5F5] rounded-lg p-2 hover:text-black", children: "About Us" }), _jsx("button", { className: "block mt-4 text-sm md:inline-block md:mt-0 rounded-lg p-2 bg-[#F5F5F5] text-black", children: _jsx(Link, { to: "/Contact", children: "Contact Us" }) }), _jsx("button", { onClick: () => {
                                                window.open("https://calendly.com/business-maxtron/30min");
                                            }, className: "block mt-4 text-sm md:inline-block md:mt-0 capitalize rounded-lg p-2 bg-[#F5F5F5]  text-black", children: "book a call" })] })] }), _jsx("div", { className: ` absolute top-6 right-5 ${isOpen ? "flex" : "hidden"}`, onClick: toggle, children: _jsx("button", { className: "focus:outline-none", style: { color: "white" }, children: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "white", width: "24px", height: "24px", children: _jsx("path", { d: "M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" }) }) }) })] })] }) }));
};
export default Navbar;
