import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import herovideo from "../assets/herovideo.mp4";
import { Link } from "react-router-dom";
import logo from "../assets/maxtronlogo.svg";
const Web3HeroSection = () => {
    return (_jsx("div", { className: "relative top-0", children: _jsx("div", { className: "mx-4 mt-4 sm:mx-6 lg:mx-8 ", children: _jsxs("div", { className: "relative h-screen w-full overflow-hidden rounded-3xl", children: [_jsxs("video", { className: "absolute top-0 left-0 w-full h-full object-cover", autoPlay: true, loop: true, muted: true, playsInline: true, children: [_jsx("source", { src: herovideo, type: "video/mp4" }), _jsx("track", { kind: "captions", src: "/captions/hero-video-captions.vtt", srcLang: "en", label: "English", default: true }), "Your browser does not support the video tag."] }), _jsx("div", { className: "absolute top-0 left-0 w-full h-full  bg-opacity-50" }), _jsxs("div", { className: "relative z-10 flex flex-col items-center sm:items-center justify-start h-full text-white p-4 sm:p-6 lg:p-16 mt-8", children: [_jsx("img", { src: logo, alt: "web3 logo", className: "w-54 h-51" }), _jsx("h2", { className: "text-2xl  sm:block sm:text-xl md:text-6xl font-normal text-center text-[#171717] mb-5", children: "Powering the Next Internet with AI & Automation" }), _jsx("p", { className: "text-lg sm:text-lg md:text-xl text-center bg-opacity-50  rounded text-[#171717] mb-12", children: "The internet is evolving- faster, more decentralized and trustless by design. At Maxtron, we're helping forward-thinking teams build in Web3 with the intelligence and automation edge they need to scale securely, compliantly and globally." }), _jsxs("div", { className: "flex flex-row sm:flex-row justify-center items-center space-x-4", children: [_jsx("input", { type: "email", placeholder: "Enter Your Email", className: " text-white border-[#FFFFFF] border font-normal md:py-3 md:px-6 rounded-full transition duration-300 w-full sm:w-auto py-2 px-3 bg-transparent outline-none placeholder:text-[#FFFFFF]" }), _jsx(Link, { to: "", className: "bg-[#7A35C1] hover:bg-indigo-200 hover:text-[#7A35C1]  font-normal md:py-3 md:px-6 rounded-full transition duration-300 w-full sm:w-auto py-2 px-3", children: _jsx("span", { children: "Connect" }) })] })] })] }) }) }));
};
export default React.memo(Web3HeroSection);
