import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Navbar from "./components/Navbars";
// import Banner from "./components/Banner";
import ContactForm from "./components/ContactForm";
// import ContactWidget from "./components/ContactWidget";
import WhatsappWidget from "./components/WhatsappWidget";
import Footer from "./components/Footer";
import Service from "./components/Services";
import AboutUs from "./components/pages/AboutUs";
import Insights from "./components/pages/Insights";
import Industries from "./components/pages/Industries";
import "./page.css";
import CaseStudyPage from "./components/pages/CaseStudyPage";
// import InternalPage from "./components/pages/InternalPage";
import { caseStudies } from "./components/elementalComponent/caseStudyData";
import CaseStudy from "./components/pages/CaseStudy";
import InternalPageDetails from "./components/pages/InternalPageDetails";
import Careers from "./components/pages/Careers";
import TokenizePage from "./components/pages/TokenizePage";
import NewHomePage from "./components/pages/NewHomePage";
import FundRaising from "./components/pages/FundRaising";
import AffiliateProgramPage from "./components/pages/AffiliateProgramPage";
import EventsPage from "./components/pages/EventsPage";
import StaffAugmentation from "./components/pages/staffAugmentation";
import OurTeam from "./components/pages/OurTeam";
import Compliance from "./components/pages/Compliance";
import Web3 from "./components/pages/Web3";
import Web3Marketing from "./components/pages/Web3Marketing";
import Blockchain from "./components/pages/Blockchain";
import ArtificialIntelligence from "./components/pages/ArtificialIntelligence";
import PrivacyPolicy from "./components/pages/PrivacyPolicy";
import PerformanceMarketing from "./components/pages/PerformanceMarketing";
import NotFound from "./components/pages/NotFound";
const Home = () => (_jsx("div", { children: _jsx(NewHomePage, {}) }));
const About = () => (_jsx("div", { children: _jsx(AboutUs, {}) }));
const Services = () => (_jsx("div", { children: _jsx(Service, {}) }));
const CareersPage = () => (_jsx("div", { children: _jsx(Careers, {}) }));
const Solutions = () => _jsx("div", { children: "Solutions Page" });
const Blog = () => _jsx("div", { children: "Blog Page" });
const Contact = () => (_jsx("div", { children: _jsx(ContactForm, {}) }));
const Book = () => _jsx("div", { children: "Book a Meeting Page" });
const App = () => {
    return (_jsxs(Router, { children: [_jsx(Navbar, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/about", element: _jsx(About, {}) }), _jsx(Route, { path: "/services", element: _jsx(Services, {}) }), _jsx(Route, { path: "/solutions", element: _jsx(Solutions, {}) }), _jsx(Route, { path: "/industries", element: _jsx(Industries, {}) }), _jsx(Route, { path: "/insights", element: _jsx(Insights, {}) }), _jsx(Route, { path: "/case-study", element: _jsx(CaseStudyPage, {}) }), _jsx(Route, { path: "/careers", element: _jsx(CareersPage, {}) }), _jsx(Route, { path: "/fund-raising", element: _jsx(FundRaising, {}) }), _jsx(Route, { path: "/our-team", element: _jsx(OurTeam, {}) }), _jsx(Route, { path: "/case-studies", element: _jsx(CaseStudy, {}) }), _jsx(Route, { path: "/tokenization", element: _jsx(TokenizePage, {}) }), _jsx(Route, { path: "/web3-development-company", element: _jsx(Web3, {}) }), _jsx(Route, { path: "/web3-crypto-marketing-agency", element: _jsx(Web3Marketing, {}) }), _jsx(Route, { path: "/blockchain-app-development-company", element: _jsx(Blockchain, {}) }), _jsx(Route, { path: "/staff-augmentation", element: _jsx(StaffAugmentation, {}) }), _jsx(Route, { path: "/affiliate", element: _jsx(AffiliateProgramPage, {}) }), _jsx(Route, { path: "/events", element: _jsx(EventsPage, {}) }), _jsx(Route, { path: "/performance-marketing", element: _jsx(PerformanceMarketing, {}) }), _jsx(Route, { path: "/compliance", element: _jsx(Compliance, {}) }), _jsx(Route, { path: "/artificial-intelligence", element: _jsx(ArtificialIntelligence, {}) }), _jsx(Route, { path: "/privacy-policy", element: _jsx(PrivacyPolicy, {}) }), _jsx(Route, { path: "/case-study/:casestudyName", element: _jsx(InternalPageDetails, { caseStudies: caseStudies }) }), _jsx(Route, { path: "/blog", element: _jsx(Blog, {}) }), _jsx(Route, { path: "/contact", element: _jsx(Contact, {}) }), _jsx(Route, { path: "/book", element: _jsx(Book, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }), _jsx(Footer, {}), _jsx(WhatsappWidget, {})] }));
};
export default App;
